name: 'Dynamic Readme'

description: ''

author: 'varunsridharan'

branding:
  icon: 'airplay'
  color: 'blue'

inputs:
  files:
    description: 'Enter Multiple by , seperated'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}